apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roll
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/patrick-men/argo-sync
    path: apps/roll/deployment
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true