apiVersion: v1
kind: PersistentVolume
metadata:
  name: insurgency-pv
  namespace: insurgency
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/insurgency
  claimRef:
    namespace: insurgency
    name: insurgency-pvc
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: insurgency-pvc
  namespace: insurgency
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi