apiVersion: v1
kind: PersistentVolume
metadata:
  name: giteadb-pv-data
  namespace: gitea
  labels:
    type: local

spec:
  storageClassName: giteadb-manual-data
  capacity:
    storage: "100Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/raiddata/gitea/postgres"
