apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: server-claim1
  name: server-claim1
  namespace: gitea
spec:
  storageClassName: gitea-manual-timezone
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}
