apiVersion: apps/v1
kind: Deployment
metadata:
  name: roll-deployment
  labels:
    app: roll
  namespace: roll

spec:
  template:
    metadata:
      name: roll-pod
      labels:
        app: roll
    spec:
      containers:
        - name: roll
          image: modem7/docker-rickroll
          ports:
            - containerPort: 8080
  replicas: 2
  selector:
    matchLabels:
      app: roll