apiVersion: v1
kind: Service
metadata:
  name: roll-nodeport
  namespace: roll
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30011
  selector:
    app: roll