apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  source:
    chart: uptime-kuma
    repoURL: https://patrick-men.github.io/kuma-uptime-helm/
    targetRevision: v0.1.2
    helm:
      releaseName: uptime-kuma
      valueFiles:
      - apps/dev/values/custom-values.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true