apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  source:
    chart: uptime-kuma
    repoURL: https://patrick-men.github.io/kuma-uptime-helm/
    targetRevision: v0.1.2
    helm:
      releaseName: uptime-kuma
      values: |
        kuma:
          name: "kuma"
          namespace: "kuma"
        deployment:
          replicas: "2"
        storage:
          pvCapacity: "5Gi"
          storageClassName: "kuma-sc"
          localPath: "/mnt/raiddata/kuma"
        service:
          type: "NodePort"
          nodePort: "32222" # In case type = NodePort
  