apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appofapps
  namespace: argocd
spec:
  project: default
  sources:
    # - repoURL: https://github.com/patrick-men/argo-sync
    #   path: apps/gitea
    #   targetRevision: HEAD

    - repoURL: https://github.com/patrick-men/argo-sync
      path: apps/kf2
      targetRevision: HEAD

    # - repoURL: https://github.com/patrick-men/argo-sync
    #   path: apps/kuma
    #   targetRevision: HEAD

    # - repoURL: https://github.com/patrick-men/argo-sync
    #   path: apps/roll
    #   targetRevision: HEAD
    
    # - repoURL: https://github.com/patrick-men/argo-sync
    #   path: apps/inss
    #   targetRevision: HEAD


    - repoURL: https://github.com/patrick-men/argo-sync
      path: apps/dev
      targetRevision: dev

      
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true