apiVersion: v1
kind: PersistentVolume
metadata:
  name: kf2-pv
  namespace: kf2
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kf2-storage
  local:
    path: /mnt/raiddata/kf2
  nodeAffinity:
    required:
     nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - patrick
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kf2-pvc
  namespace: kf2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kf2-storage
  resources:
    requests:
      storage: 50Gi