name: 'PRtoMain'

on:
  pull_request:

jobs:
  check_main:
    runs-on: ubuntu-latest
    steps:
      - name: Check main
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          echo "ERROR: You can only merge to main from dev."
          exit 1
