apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  sources:
    repoURL: https://github.com/patrick-men/argo-sync
    path: apps/gitea
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc